name: Validate Branch Name

on: 
  pull_request:
    types: [opened, synchronize]

jobs:
  branch-naming:
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch name
        run: |
          if [[ $GITHUB_REF != refs/heads/feature-* ]]; then
            echo "Branch name must start with 'feature-'";
            exit 1;
          fi
